#version 450
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_GOOGLE_include_directive : enable

// Based on AMD FidelityFX FSR 1 sample (MIT). See third_party/fsr1/LICENSE.

layout(set = 0, binding = 0) uniform const_buffer {
  uvec4 Const0;
  uvec4 Const1;
  uvec4 Const2;
  uvec4 Const3;
  uvec4 Sample;
};

#define A_GPU 1
#define A_GLSL 1
#define SAMPLE_SLOW_FALLBACK 1

#include "ffx_a.h"

layout(set = 0, binding = 1) uniform texture2D InputTexture;
layout(set = 0, binding = 2, rgba8) uniform image2D OutputTexture;
layout(set = 0, binding = 3) uniform sampler InputSampler;

#if SAMPLE_EASU
#define FSR_EASU_F 1
AF4 FsrEasuRF(AF2 p) { return textureGather(sampler2D(InputTexture, InputSampler), p, 0); }
AF4 FsrEasuGF(AF2 p) { return textureGather(sampler2D(InputTexture, InputSampler), p, 1); }
AF4 FsrEasuBF(AF2 p) { return textureGather(sampler2D(InputTexture, InputSampler), p, 2); }
#endif

#if SAMPLE_RCAS
#define FSR_RCAS_F
AF4 FsrRcasLoadF(ASU2 p) { return texelFetch(sampler2D(InputTexture, InputSampler), ASU2(p), 0); }
void FsrRcasInputF(inout AF1 r, inout AF1 g, inout AF1 b) {}
#endif

#include "ffx_fsr1.h"

void CurrFilter(AU2 pos) {
#if SAMPLE_EASU
  AF3 c;
  FsrEasuF(c, pos, Const0, Const1, Const2, Const3);
  if (Sample.x == 1) c *= c;
  imageStore(OutputTexture, ASU2(pos), AF4(c, 1));
#endif
#if SAMPLE_RCAS
  AF3 c;
  FsrRcasF(c.r, c.g, c.b, pos, Const0);
  if (Sample.x == 1) c *= c;
  imageStore(OutputTexture, ASU2(pos), AF4(c, 1));
#endif
}

layout(local_size_x = 64) in;
void main() {
  AU2 gxy = ARmp8x8(gl_LocalInvocationID.x) + AU2(gl_WorkGroupID.x << 4u, gl_WorkGroupID.y << 4u);
  CurrFilter(gxy);
  gxy.x += 8u;
  CurrFilter(gxy);
  gxy.y += 8u;
  CurrFilter(gxy);
  gxy.x -= 8u;
  CurrFilter(gxy);
}
